version: '3.8'

services:
  litholicht-konfigurator:
    image: git.tecmaxx.de/mamotec/litholicht-konfigurator/app:latest
    container_name: litholicht-konfigurator
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - ODOO_URL=https://litholicht.de
      - ODOO_API_KEY=${ODOO_API_KEY}
